package Y_PSC.UNIT_II.DSA_III;

import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class AlanFrequency {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        int n = scanner.nextInt();
        String str = scanner.next();
        characterCount(str);
    }

    public static void characterCount(String inputString) {
        HashMap<Character, Integer> charCountMap = new HashMap<>();
        char[] strArray = inputString.toCharArray();
        for (char c : strArray) {
            if (charCountMap.containsKey(c)) {
                charCountMap.put(c, charCountMap.get(c) + 1);
            } else {
                charCountMap.put(c, 1);
            }
        }
        for (Map.Entry<Character, Integer> e : charCountMap.entrySet()) {
            System.out.println(e.getKey() + "-" + e.getValue());

        }

    }
}
//        Scanner scanner = new Scanner(System.in);
//        int N = scanner.nextInt();
//        String str = scanner.next();
//        res(N, str);
//    }
//
//    static void res(int N, String str) {
//        HashMap<Character, Integer> hashMap = new HashMap<>();
//        char[] arr = str.toCharArray();
//        for (char c : arr) {
//            if (hashMap.containsKey(c)) {
//                hashMap.put(c, hashMap.get(c) + 1);
//            } else {
//                hashMap.put(c, 1);
//            }
//        }
//
//        for (Map.Entry<Character, Integer> map : hashMap.entrySet()) {
//            System.out.println(map.getKey() + "-" + map.getValue());
//        }
//    }
//}
/**
 * Alan & Frequency
 * Description
 * <p>
 * Alan Turing, the mathematician, is trying to break the encrypted messages of the German Troops, generated by their encryption device "Enigma". To find the distribution of characters, he needs to find out how many times a particular character appears in a string. But, to feed the data into his computer, "Christopher", he needs the data in lexicographic order, that is, in alphabetical order. Since, he is busy making "Christopher" better, he asks you for help. Help Alan find the frequency of characters in the encrypted strings in alphabetical order. The string contains only lower case alphabets.
 * <p>
 * <p>
 * Input
 * The first line contains N, the length of the string, and the next line contains the string itself.
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * 1 <= N<=100
 * <p>
 * <p>
 * Output
 * For each unique character in the string, print the character along with its frequency in the encrypted string, separated by '-' , on a new line.
 * <p>
 * <p>
 * Sample Input 1
 * <p>
 * 4
 * aman
 * Sample Output 1
 * <p>
 * a-2
 * m-1
 * n-1
 */
